<?php

return $houses = [
    [   
        'user_id'=>1,
        'title'=> 'Masseria De Vivo',
        'description'=> 'Situated in Manduria, La Filumena features accommodation with a balcony and free WiFi. Towels and bed linen are available',
        'rooms'=> 12,
        'beds'=> 10,
        'bathrooms'=> 3,
        'square_mt'=> 1000,
        'street'=> 'via Donadio',
        'city'=> 'Manduria',
        'house_number'=> 6,
        'postal_code' => '74024',
        'latitude'=>  40.4022,
        'longitude'=> 17.63788,
        'thumbnail'=> 'houses_img/2LAURA-esterno-2.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Stamberga Giulia',
        'description'=> 'stamberga delle stamberghe top quality very recomended',
        'rooms'=> 7,
        'beds'=> 4,
        'bathrooms'=> 2,
        'square_mt'=> 350,
        'street'=> 'via della fiammetta',
        'city'=> 'Rosignano Solvay',
        'house_number'=> 23,
        'postal_code' => '57016',
        'latitude'=>  43.39213,
        'longitude'=> 10.45436,
        'thumbnail'=> 'houses_img/1384302.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Sottoponte Ferrini',
        'description'=> 'un bel ponte devo dire, sì esatto',
        'rooms'=> 1,
        'beds'=> 1,
        'bathrooms'=> 1,
        'square_mt'=> 15,
        'street'=> 'Via Leonardo Da Vinci',
        'city'=> 'Firenze',
        'house_number'=> 1,
        'postal_code' => '50132',
        'latitude'=>  43.78235,
        'longitude'=> 11.26575,
        'thumbnail'=> 'houses_img/01-18.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Poggio Bacoli',
        'description'=> 'questa è la casa template di domenico eheh',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via germania',
        'city'=> 'Latina',
        'house_number'=> 18,
        'postal_code' => '04100',
        'latitude'=>  41.45826,
        'longitude'=> 12.88399,
        'thumbnail'=> 'houses_img/d3.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Casa ad Arcore di Gabry :P',
        'description'=> 'siamo a corto di descrizioni',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via maffei',
        'city'=> 'Sondrio',
        'house_number'=> 63,
        'postal_code' => '23100',
        'latitude'=>  46.16304,
        'longitude'=> 9.86197,
        'thumbnail'=> 'houses_img/montagna-baita_seconda_casa_neve_chalet_min.jpeg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Masseria De Vivo',
        'description'=> 'Situated in Manduria, La Filumena features accommodation with a balcony and free WiFi. Towels and bed linen are available',
        'rooms'=> 12,
        'beds'=> 10,
        'bathrooms'=> 3,
        'square_mt'=> 1000,
        'street'=> 'via simone martini',
        'city'=> 'Milano',
        'house_number'=> 2,
        'postal_code' => '20143',
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'houses_img/2LAURA-esterno-2.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Stamberga Giulia',
        'description'=> 'stamberga delle stamberghe top quality very recomended',
        'rooms'=> 7,
        'beds'=> 4,
        'bathrooms'=> 2,
        'square_mt'=> 350,
        'street'=> 'via Giulia',
        'city'=> 'Roma',
        'house_number'=> 6,
        'postal_code' => '00186',
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'houses_img/1384302.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Sottoponte Ferrini',
        'description'=> 'un bel ponte devo dire, sì esatto',
        'rooms'=> 1,
        'beds'=> 1,
        'bathrooms'=> 1,
        'square_mt'=> 15,
        'street'=> 'Viale domenico vitali',
        'city'=> 'Bellagio',
        'house_number'=> 2,
        'postal_code' => '22021',
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'houses_img/01-18.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Poggio Bacoli',
        'description'=> 'questa è la casa template di domenico eheh',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via saragozza',
        'city'=> 'Bologna',
        'house_number'=> 2,
        'postal_code' => '40123',
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'houses_img/d3.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Casa ad Arcore di Gabry :P',
        'description'=> 'siamo a corto di descrizioni',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via de vivo',
        'city'=> 'Castellabate',
        'house_number'=> 2,
        'postal_code' => 84048,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'houses_img/montagna-baita_seconda_casa_neve_chalet_min.jpeg',
        'visibility'=> true,
    ],
];