<?php

return $houses = [
    [   
        'user_id'=>1,
        'title'=> 'Masseria De Vivo',
        'description'=> 'Situated in Manduria, 36 km from Taranto Sotterranea, 38 km from National Archaeological Museum of Taranto Marta and 38 km from Castello Aragonese, La Filumena features accommodation with a balcony and free WiFi. Housed in a building dating from 2020, this holiday home is 40 km from the Taranto Cathedral. The air-conditioned holiday home consists of 1 bedroom, a living room, a fully equipped kitchen with a fridge, and 2 bathrooms with a bidet and a hairdryer. Towels and bed linen are available',
        'rooms'=> 12,
        'beds'=> 10,
        'bathrooms'=> 3,
        'square_mt'=> 1000,
        'street'=> 'via Giovanni Minzoni',
        'city'=> 'Manduria',
        'house_number'=> 71,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://www.uozhouse.it/wp-content/uploads/2020/05/2LAURA-esterno-2.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Stamberga Giulia',
        'description'=> 'stamberga delle stamberghe top quality very recomended',
        'rooms'=> 7,
        'beds'=> 4,
        'bathrooms'=> 2,
        'square_mt'=> 350,
        'street'=> 'via Roma',
        'city'=> 'Livorno',
        'house_number'=> 17,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://gallery-cdn.tiscali.it/repository/1385/650x468/1384302.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>2,
        'title'=> 'Sottoponte Ferrini',
        'description'=> 'un bel ponte devo dire, sì esatto',
        'rooms'=> 1,
        'beds'=> 1,
        'bathrooms'=> 1,
        'square_mt'=> 15,
        'street'=> 'Viale Sogni Infranti',
        'city'=> 'Firenze',
        'house_number'=> 1,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://www.geniuslociarchitettura.it/wp-content/uploads/2019/05/01-18.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>2,
        'title'=> 'Poggio Bacoli',
        'description'=> 'questa è la casa template di domenico eheh',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via Lazio',
        'city'=> 'Latina',
        'house_number'=> 18,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://media.tacdn.com/media/attractions-splice-spp-674x446/06/75/c1/d3.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>3,
        'title'=> 'Casa ad Arcore di Gabry :P',
        'description'=> 'siamo a corto di descrizioni',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via Milano',
        'city'=> 'Cinisello Balsamo',
        'house_number'=> 18,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://www.immobiliare.it/news/app/uploads/2022/01/montagna-baita_seconda_casa_neve_chalet_min.jpeg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>3,
        'title'=> 'Villa De Vivo',
        'description'=> 'Situated in Manduria, 36 km from Taranto Sotterranea, 38 km from National Archaeological Museum of Taranto Marta and 38 km from Castello Aragonese, La Filumena features accommodation with a balcony and free WiFi. Housed in a building dating from 2020, this holiday home is 40 km from the Taranto Cathedral. The air-conditioned holiday home consists of 1 bedroom, a living room, a fully equipped kitchen with a fridge, and 2 bathrooms with a bidet and a hairdryer. Towels and bed linen are available',
        'rooms'=> 12,
        'beds'=> 10,
        'bathrooms'=> 3,
        'square_mt'=> 1000,
        'street'=> 'via Giovanni Minzoni',
        'city'=> 'Manduria',
        'house_number'=> 71,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://www.uozhouse.it/wp-content/uploads/2020/05/2LAURA-esterno-2.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>4,
        'title'=> 'Stamberga Giulia',
        'description'=> 'stamberga delle stamberghe top quality very recomended',
        'rooms'=> 7,
        'beds'=> 4,
        'bathrooms'=> 2,
        'square_mt'=> 350,
        'street'=> 'via Roma',
        'city'=> 'Livorno',
        'house_number'=> 17,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://gallery-cdn.tiscali.it/repository/1385/650x468/1384302.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>4,
        'title'=> 'Sottoponte Ferrini',
        'description'=> 'un bel ponte devo dire, sì esatto',
        'rooms'=> 1,
        'beds'=> 1,
        'bathrooms'=> 1,
        'square_mt'=> 15,
        'street'=> 'Viale Sogni Infranti',
        'city'=> 'Firenze',
        'house_number'=> 1,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://www.geniuslociarchitettura.it/wp-content/uploads/2019/05/01-18.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>5,
        'title'=> 'Poggio Bacoli',
        'description'=> 'questa è la casa template di domenico eheh',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via Lazio',
        'city'=> 'Latina',
        'house_number'=> 18,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://media.tacdn.com/media/attractions-splice-spp-674x446/06/75/c1/d3.jpg',
        'visibility'=> true,
    ],
    [   
        'user_id'=>5,
        'title'=> 'Casa ad Arcore di Gabry :P',
        'description'=> 'siamo a corto di descrizioni',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via Milano',
        'city'=> 'Cinisello Balsamo',
        'house_number'=> 18,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://www.immobiliare.it/news/app/uploads/2022/01/montagna-baita_seconda_casa_neve_chalet_min.jpeg',
        'visibility'=> true,
    ],
];