<?php

return $houses = [
    [   
        'user_id'=>1,
        'title'=> 'Villa De Vivo',
        'description'=> 'Situated in Manduria, 36 km from Taranto Sotterranea, 38 km from National Archaeological Museum of Taranto Marta and 38 km from Castello Aragonese, La Filumena features accommodation with a balcony and free WiFi. Housed in a building dating from 2020, this holiday home is 40 km from the Taranto Cathedral. The air-conditioned holiday home consists of 1 bedroom, a living room, a fully equipped kitchen with a fridge, and 2 bathrooms with a bidet and a hairdryer. Towels and bed linen are available',
        'rooms'=> 12,
        'beds'=> 10,
        'bathrooms'=> 10,
        'square_mt'=> 1000,
        'street'=> 'via Giovanni Minzoni',
        'city'=> 'Manduria',
        'house_number'=> 71,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://ibb.co/4WkYbVL',
        'visibility'=> true,
    ],
    [   
        'user_id'=>2,
        'title'=> 'Stamberga Giulia',
        'description'=> 'Situated in Manduria, 36 km from Taranto Sotterranea, 38 km from National Archaeological Museum of Taranto Marta and 38 km from Castello Aragonese, La Filumena features accommodation with a balcony and free WiFi. Housed in a building dating from 2020, this holiday home is 40 km from the Taranto Cathedral. The air-conditioned holiday home consists of 1 bedroom, a living room, a fully equipped kitchen with a fridge, and 2 bathrooms with a bidet and a hairdryer. Towels and bed linen are available',
        'rooms'=> 7,
        'beds'=> 4,
        'bathrooms'=> 2,
        'square_mt'=> 350,
        'street'=> 'via Roma',
        'city'=> 'Livorno',
        'house_number'=> 17,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://ibb.co/4WkYbVL',
        'visibility'=> true,
    ],
    [   
        'user_id'=>1,
        'title'=> 'Sottoponte Ferrini',
        'description'=> 'Situated in Manduria, 36 km from Taranto Sotterranea, 38 km from National Archaeological Museum of Taranto Marta and 38 km from Castello Aragonese, La Filumena features accommodation with a balcony and free WiFi. Housed in a building dating from 2020, this holiday home is 40 km from the Taranto Cathedral. The air-conditioned holiday home consists of 1 bedroom, a living room, a fully equipped kitchen with a fridge, and 2 bathrooms with a bidet and a hairdryer. Towels and bed linen are available',
        'rooms'=> 1,
        'beds'=> 1,
        'bathrooms'=> 1,
        'square_mt'=> 15,
        'street'=> 'Viale Sogni Infranti',
        'city'=> 'Firenze',
        'house_number'=> 1,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://ibb.co/4WkYbVL',
        'visibility'=> true,
    ],
    [   
        'user_id'=>2,
        'title'=> 'Poggio Bacoli',
        'description'=> 'Situated in Manduria, 36 km from Taranto Sotterranea, 38 km from National Archaeological Museum of Taranto Marta and 38 km from Castello Aragonese, La Filumena features accommodation with a balcony and free WiFi. Housed in a building dating from 2020, this holiday home is 40 km from the Taranto Cathedral. The air-conditioned holiday home consists of 1 bedroom, a living room, a fully equipped kitchen with a fridge, and 2 bathrooms with a bidet and a hairdryer. Towels and bed linen are available',
        'rooms'=> 8,
        'beds'=> 6,
        'bathrooms'=> 2,
        'square_mt'=> 390,
        'street'=> 'via Lazio',
        'city'=> 'Latina',
        'house_number'=> 18,
        'latitude'=>  1.01,
        'longitude'=> 1.02,
        'thumbnail'=> 'https://ibb.co/4WkYbVL',
        'visibility'=> true,
    ],
];